services:
  app:
    container_name: kakeibo
    image: ghcr.io/manosriram/kakeibo:latest
    # volumes:
      # - ./data:/app/data
    ports:
      - "5464:8080"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 2s
    restart: always
