services:
  kakeibo:
    container_name: kakeibo
    image: ghcr.io/manosriram/kakeibo:latest
    # volumes:
      # - ./data:/app/data
    ports:
      - "5464:8080"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
    networks:
      - kakeibo_network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_server
    restart: always
    ports:
      - "6333:6333" # HTTP API
      - "6334:6334" # gRPC API
    volumes:
      - ./qdrant_storage:/qdrant/storage
    networks:
      - kakeibo_network

networks:
  kakeibo_network:
    driver: bridge

